# M11: Ingress TLS Ciphers (CIS Compliance)
# Documentation: https://sebrandon1.github.io/compliance-scripts/versions/4.21/groups/M11.html
#
# This configures custom TLS cipher suites for the Ingress Controller.
#
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  tlsSecurityProfile:
    type: Custom
    custom:
      ciphers:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
      minTLSVersion: VersionTLS12
